# GenerateGitVersion.cmake — script-mode CMake invoked every build.
#
# Inputs (via -D on the command line):
#   SOURCE_DIR  : project source root (used as the git working directory)
#   BINARY_DIR  : project build root (output is written under generated/)
#
# Output:
#   ${BINARY_DIR}/generated/mrtk_git_version.c
#     Defines `const char mrtklib_git_hash_str[]` with the result of
#     `git describe --always --dirty --tags --match 'v*'`, or "unknown"
#     when git is unavailable or SOURCE_DIR is not a git checkout
#     (tarball builds).
#
# The file is only rewritten when the resolved hash changes, so unchanged
# builds do not retrigger compilation of dependent translation units.

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED BINARY_DIR)
    message(FATAL_ERROR "GenerateGitVersion.cmake requires -DSOURCE_DIR and -DBINARY_DIR")
endif()

set(_git_hash "unknown")

find_program(GIT_EXECUTABLE git)
if(GIT_EXECUTABLE AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --always --dirty --tags --match "v*"
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE _git_describe
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _git_rc
    )
    if(_git_rc EQUAL 0 AND _git_describe)
        set(_git_hash "${_git_describe}")
    endif()
endif()

set(_out_dir  "${BINARY_DIR}/generated")
set(_out_file "${_out_dir}/mrtk_git_version.c")
file(MAKE_DIRECTORY "${_out_dir}")

set(_new_content
"/* Auto-generated by cmake/GenerateGitVersion.cmake — do not edit. */
const char mrtklib_git_hash_str[] = \"${_git_hash}\";
")

set(_old_content "")
if(EXISTS "${_out_file}")
    file(READ "${_out_file}" _old_content)
endif()

if(NOT "${_old_content}" STREQUAL "${_new_content}")
    file(WRITE "${_out_file}" "${_new_content}")
    message(STATUS "mrtk git hash: ${_git_hash}")
endif()
